# -*- coding: utf-8 -*-
"""Computation_with_NumPy_and_N_Dimensional_Arrays_Day_76

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1axZmgBqOvVKN2ZJ3oKL6U9CBfFI0wykz

# Introduction

In this notebook we'll learn how to use NumPy to work with numerical data. 

<img src="https://i.imgur.com/dZ1XE9o.png" width=400>

# Import Statements
"""

import numpy as np

import matplotlib.pyplot as plt
from scipy import misc # contains an image of a racoon!
from PIL import Image # for reading image files

"""# Understanding NumPy's ndarray

NumPy's most amazing feature is the **powerful** ndarray.

<img src="https://i.imgur.com/1IUqnxX.png" width=200>

#### 1-Dimensional Arrays (Vectors)
"""

my_array = np.array([1.1, 9.2, 8.1, 4.7])
my_array

print(my_array.shape)
print(my_array[2])
print(my_array.ndim)

"""#### 2-Dimensional Arrays (Matrices)"""

array_2d = np.array([[1, 2, 3, 9], 
                     [5, 6, 7, 8]])

print(f'array_2d has {array_2d.ndim} dimensions')
print(f'Its shape is {array_2d.shape}')
print(f'It has {array_2d.shape[0]} rows and {array_2d.shape[1]} columns')
print(array_2d)

"""#### N-Dimensional Arrays (Tensors)

**Challenge**: 
* How many dimensions does the array below have? 
* What is its shape (i.e., how many elements are along each axis)?
* Try to access the value `18` in the last line of code.
* Try to retrieve a 1 dimensional vector with the values `[97, 0, 27, 18]`
* Try to retrieve a (3,2) matrix with the values `[[ 0,  4], [ 7,  5], [ 5, 97]]`

*Hint*: You can use the `:` operator just as with Python Lists.
"""

mystery_array = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                        
                         [[7, 86, 6, 98],
                          [5, 1, 0, 4]],
                          
                          [[5, 36, 32, 48],
                           [97, 0, 27, 18]]])

# Note all the square brackets!

print(mystery_array.shape)
# arrays are just lists inside lists, so you can find specific data by calling it with []
print(f'Last entry = {mystery_array[2][1][3]}')
# can also do like this
print(f'Last entry = {mystery_array[2,1,3]}')
print(f'Last set of data = {mystery_array[2,:]}')
print(f'second set of data = \n{mystery_array[1]}')
print(f'One dimensional vector she wanted = {mystery_array[2,1,:]}')

# List Comprehension that does a for_loop inside a for_loop
new_matrix = [[cell[0] for cell in item] for item in mystery_array]
new_matrix

# Her way to get first element on the 3rd axis
mystery_array[:,:,0]

"""# NumPy Mini-Challenges

#### **Challenge 1**: Use [`.arange()`](https://numpy.org/devdocs/reference/generated/numpy.arange.html)to createa a vector `a` with values ranging from 10 to 29. You should get this:

`print(a)`

`[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]`
"""

# .arange doesn't include the stop number
a = np.arange(10,30)
print(a)

"""#### **Challenge 2**: Use Python slicing techniques on `a` to:
* Create an array containing only the last 3 values of `a`
* Create a subset with only the 4th, 5th, and 6th values
* Create a subset of `a` containing all the values except for the first 12 (i.e., `[22, 23, 24, 25, 26, 27, 28, 29]`)
* Create a subset that only contains the even numbers (i.e, every second number)
"""

print(a[-3:])
print(a[3:6])
print(a[12:])
print(a[::2])

"""#### **Challenge 3**:Reverse the order of the values in `a`, so that the first element comes last:

`[29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10]`


If you need a hint, you can check out this part of the [NumPy beginner's guide](
https://numpy.org/devdocs/user/absolute_beginners.html#how-to-reverse-an-array)
"""

print(a[::-1])
# or using numpy method:
print(np.flip(a))
# can reverse everything, just rows, or just columns, etc. specific with axis
print(np.flip(a, axis=0))
# can reverse just one row/columns (for arrays with greater than 1 dimension)
#print(np.flip(a[:], axis=0))

"""#### **Challenge 4**: Print out all the indices of the non-zero elements in this array: [6,0,9,0,0,5,0]"""

new_a = np.array([6,0,9,0,0,5,0])

 # Simpler way, just create condition inside the bracket
 print(new_a[new_a != 0])
 
 # new_a.nonzero() creates an array with the indices for the values that matched. Pass it back into new_a and you get the values
 print(new_a.nonzero())
 print(np.nonzero(new_a))
 print(new_a[new_a.nonzero()])

"""#### **Challenge 5**: Use NumPy to generate a 3x3x3 array with random numbers

Hint: Use the [`.random()` function](https://numpy.org/doc/stable/reference/random/index.html?highlight=random#module-numpy.random)
"""

from numpy.random import default_rng

rng = default_rng()
# vals = rng.standard_normal(10)
# more_vals = rng.standard_normal(10)
rng.integers(100, size=(3,3,3))

"""#### **Challenge 6**: Use [`.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) to create a vector `x` of size 9 with values spaced out evenly between 0 to 100 (both included)."""

x = np.linspace(0, 100, num=9, endpoint=True)
x

"""#### **Challenge 7**: Use [`.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) to create another vector `y` of size 9 with values between -3 to 3 (both included). Then plot `x` and `y` on a line chart using Matplotlib."""

y = np.linspace(-3, 3, num=9, endpoint=True)
plt.plot(x, y)
plt.show()

"""#### **Challenge 8**: Use NumPy to generate an array called `noise` with shape 128x128x3 that has random values. Then use Matplotlib's [`.imshow()`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imshow.html) to display the array as an image. """

# 128px by 128px, with 3 data values, randomly between 0 and 255, mimicks the RGB values of an image!
noise = rng.integers(256,size=(128, 128, 3))
print(noise)
plt.imshow(noise)

"""# Linear Algebra with Vectors"""

v1 = np.array([4, 5, 2, 7])
v2 = np.array([2, 1, 3, 3])

# Python Lists vs ndarrays
list1 = [4, 5, 2, 7]
list2 = [2, 1, 3, 3]

display(v1 + v2)
display(list1 + list2)

v1 * v2

"""# Broadcasting and Scalars

"""

# Broadcasting
v1 + 22

# Scalars
v2 * 20

"""# Matrix Multiplication with @ and .matmul()

<img src=https://i.imgur.com/LCdhmi8.png width=350>
"""

a1 = np.array([[1, 3],
               [0, 1],
               [6, 2],
               [9, 7]])

b1 = np.array([[4, 1, 3],
               [5, 8, 5]])

print(f'{a1.shape}: a has {a1.shape[0]} rows and {a1.shape[1]} columns.')
print(f'{b1.shape}: b has {b1.shape[0]} rows and {b1.shape[1]} columns.')
print('Dimensions of result: (4x2)*(2x3)=(4x3)')

"""**Challenge**: Let's multiply `a1` with `b1`. Looking at the wikipedia example above, work out the values for c12 and c33 on paper. Then use the [`.matmul()`](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) function or the `@` operator to check your work. """

c = np.matmul(a1, b1)
c

# shorthand operation for mat mul
a1 @ b1

"""# Manipulating Images as ndarrays

"""

# Randomly supplied pic
img = misc.face()

# Use .imshow to display a picture from array
plt.imshow(img)

"""**Challenge**: What is the data type of `img`? Also, what is the shape of `img` and how many dimensions does it have? What is the resolution of the image?"""

type(img)

# The shape is also the resolution, as each vector is a pixel
img.shape

img.ndim

"""**Challenge**: Convert the image to black and white. The values in our `img` range from 0 to 255. 
* Divide all the values by 255 to convert them to sRGB, where all the values are between 0 and 1. 
* Next, multiply the sRGB array by the `grey_vals` to convert the image to grey scale. 
* Finally use Matplotlib's [`.imshow()`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imshow.html) together with the colormap parameter set to gray `cmap=gray` to look at the results. 
"""

# The special conversion of RGB to turn it into greyscale and keep everything else ok
grey_vals = np.array([0.2126, 0.7152, 0.0722])

# Note: Need to do @ multiply rather than simple multiply * since it's a matrix
sRGB = img / 255
greyscale_img = sRGB @ grey_vals

plt.imshow(greyscale_img, cmap='gray')

"""**Challenge**: Can you manipulate the images by doing some operations on the underlying ndarrays? See if you can change the values in the ndarray so that:

1) You flip the grayscale image upside down

<img src=https://i.imgur.com/r36CigD.png>

2) Rotate the colour image

<img src=https://i.imgur.com/IiNylco.png>

3) Invert (i.e., solarize) the colour image. To do this you need to converting all the pixels to their "opposite" value, so black (0) becomes white (255).

<img src=https://i.imgur.com/cfFbuex.png>

#### Challenge Solutions
"""

plt.imshow(np.flip(greyscale_img), cmap='gray')

# Original Shape(768, 1024, 3)
# np.reshape(greyscale_img, (1024, 768, 3))
# Just use the rot90 function
plt.imshow(np.rot90(greyscale_img), cmap='gray')

# print(img)
# print("--------------------------------")
# print((img - (255,255,255)))
inverse_colors = np.absolute(img - (255,255,255))
plt.imshow(inverse_colors)

# simpler way:
solar_img = 255 - img
plt.imshow(solar_img)

"""# Use your Own Image!"""

# Save jpeg to variable
file_name = 'yummy_macarons.jpg'

"""#### Use PIL to open """

# Use PIL Image.open to turn jpeg into image that Numpy can work with, then pass it into np.array
my_img = Image.open(file_name)

img_array = np.array(my_img)

img_array.ndim

img_array.shape

# Shows the inverse color of the pic
plt.imshow(255 - img_array)